### ISSUE TITLE
usage examples

### ISSUE THREAD

**Issue by groundbreaker08** [enniel/ami#1]
Hi, do you have any snippets on how to send action thru this?

**Comment by enniel** [comment]
Use ami:action command. Example:

```
Artisan::call('ami:action', [
     'action' => 'Originate',
     '--arguments' => [
           "Callerid:$callerId",
           "Channel:Local/$phoneNumber@from-internal",
           "Context:from-c2call2",
           "Priority:1",
           "WaitTime:10",
           "Async:true"
    ]
]);
```

**Comment by enniel** [comment]
Use ami:sms and ami:ussd for sending sms and ussd. For sending long messages use --pdu mode.

**Comment by robertmylne** [comment]
Hi, when the events are triggered what do I add in the array to send the event data to another file to process it?
There are a few things I want to achieve :
- get all the external incoming calls info and process it ( match incoming number with existing customer in our database )
- get a listing of all the calls received by a certain extension  
Which events do I need to be able to get or filter incoming calls details ?

Thank you
```
return [
    'host' => '192.168.0.1',
    'port' => 1111,
    'username' => 'username',
    'secret' => 'secret',
    'dongle' => [
        'sms' => [
            'device' => null,
        ],
    ],
    'events' => [
        'AGIExec' => [
            // what do I put here???
        ],
        'AgentConnect' => [
        ],
        'AgentComplete' => [
        ],
        'Agentlogin' => [
        ],
        'Agentlogoff' => [
        ],
```

**Comment by enniel** [comment]
@robertmylne You can see example in repo https://github.com/enniel/ami-log (Tested on Asterisk 1.8). This package logging events in database.

**Comment by robertmylne** [comment]
Thanks :)

**Comment by robertmylne** [comment]
Which event is triggered when a person picks up the phone? I found this in the docs but it doesn't seem to be in your events list "https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_Pickup"

**Comment by enniel** [comment]
@robertmylne add your events to the configuration file and listen them
```php
// config/ami.php

...
'YourEvent' => [
  // other custom options
  ....
]
...
```

```php
// Providers/EventServiceProvider.php or Listeners/AmiBroadcaster.php
Event::listen('ami.events.YourEvent', function ($event, $otherCustomOptions) {
   \Log::info('Event '.$event->getName().' fired');
});
...

**Comment by robertmylne** [comment]
How do I fire a test event? The listener does not seem to be catching the events.

**Comment by mariapaulinar** [comment]
Fire events not working. Somebody help me :(

**Comment by ghost** [comment]
@enniel Hi, could yo explain how ami-log works? I can't understand how you create the models and then save it in the DB.

Thx you so much.

P.D: Sorry for my english.

**Comment by enniel** [comment]
@JorgeDam You can use this code for saving events:

```php
Event::listen('ami.events.EventName', function ($event) {
  $saved = YourModel::create($event->getProperties())
})
```
