### ISSUE TITLE
Bug In Artisan::call('ami:action')

### ISSUE THREAD

**Issue by zlin143** [enniel/ami#12]
hi i congratulate you for the ami package

But I found a little bug in it when i use Send ami action with this code it dont send action to asterisk 

Artisan::call('ami:action', [
    'action'      => action,
    '--arguments' => [
        key => value
        ...
    ]
]);

but with this one it send as expected , mind the colon between key and the value

Artisan::call('ami:action', [
    'action'      => action,
    '--arguments' => [
        key **:** value
               ...
    ]
]);

**Comment by enniel** [comment]
Thank you @zlin143! I'm fixed them.
